# 北上广深租房市场数据分析

## 第六部分：行政区整租市场分析

In [2]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path("../data/processed/rent_cleaned.csv")

df = pd.read_csv(DATA_PATH)

print("数据规模：", df.shape)

数据规模： (11978, 26)

## 一、建立整租分析数据

In [3]:
# 单独建立整租分析数据
entire_df = df[
    df["type"] == "整租"
].copy()

district_count = len(
    entire_df[["city", "dist"]].drop_duplicates()
)

print("整租房源数量：", len(entire_df))
print("整租城市数量：", entire_df["city"].nunique())
print("整租行政区数量：", district_count)

整租房源数量： 11564
整租城市数量： 4
整租行政区数量： 49

## 二、检查行政区样本分布

In [4]:
# 统计每个城市各行政区的整租房源数量
district_counts = entire_df.groupby(
    ["city", "dist"]
).size()

district_counts = district_counts.reset_index()

district_counts.columns = [
    "city",
    "dist",
    "整租房源数量"
]

district_counts = district_counts.sort_values(
    by=["city", "整租房源数量"],
    ascending=[True, False]
)

district_counts = district_counts.reset_index(
    drop=True
)

district_counts

   city   dist  整租房源数量
0    上海     浦东     791
1    上海     闵行     286
2    上海     松江     261
3    上海     徐汇     214
4    上海     普陀     191
5    上海     嘉定     189
6    上海     长宁     180
7    上海     青浦     173
8    上海     宝山     167
9    上海     黄浦     111
10   上海     杨浦     108
11   上海     静安      91
12   上海     闸北      90
13   上海     虹口      78
14   上海     奉贤      57
15   上海     金山       4
16   上海     崇明       1
17   北京     朝阳    1047
18   北京     海淀     328
19   北京     丰台     319
20   北京     大兴     221
21   北京     通州     219
22   北京     西城     198
23   北京     昌平     170
24   北京     房山     111
25   北京     顺义     107
26   北京    门头沟      91
27   北京     东城      64
28   北京    石景山      61
29   北京  亦庄开发区      56
30   广州     白云     662
31   广州     番禺     552
32   广州     天河     506
33   广州     增城     369
34   广州     海珠     263
35   广州     越秀     254
36   广州     荔湾     220
37   广州     南沙      51
38   广州     从化      21
39   深圳    宝安区     575
40   深圳    龙岗区     557
41   深圳    南山区     530
42   深圳    福田区     370
43   深圳    龙华区     317
44   深圳    罗湖区     228
45   深圳    光明区      68
46   深圳    盐田区      26
47   深圳    坪山区       9
48   深圳   大鹏新区       2

In [5]:
# 汇总各城市行政区的整租样本量
district_sample_summary = district_counts.groupby(
    "city"
)["整租房源数量"].describe().round(2)

district_sample_summary

      count    mean     std   min    25%    50%    75%     max
city
上海     17.0  176.00  178.00   1.0   90.0  167.0  191.0   791.0
北京     13.0  230.15  262.18  56.0   91.0  170.0  221.0  1047.0
广州      9.0  322.00  219.98  21.0  220.0  263.0  506.0   662.0
深圳     10.0  268.20  235.05   2.0   36.5  272.5  490.0   575.0

In [7]:
# 找出整租样本少于30条的行政区
small_sample_districts = district_counts[
    district_counts["整租房源数量"] < 30
].copy()

small_sample_districts

   city  dist  整租房源数量
15   上海    金山       4
16   上海    崇明       1
38   广州    从化      21
46   深圳   盐田区      26
47   深圳   坪山区       9
48   深圳  大鹏新区       2

In [9]:
# 找出整租样本不少于30条的行政区
eligible_districts = district_counts[
    district_counts["整租房源数量"] >= 30
].copy()

# 重新生成连续行号
eligible_districts = eligible_districts.reset_index(
    drop=True
)

print("全部行政区数量：", len(district_counts))
print("参与排名的行政区数量：", len(eligible_districts))
print("样本不足的行政区数量：", len(small_sample_districts))

eligible_districts

全部行政区数量： 49
参与排名的行政区数量： 43
样本不足的行政区数量： 6

   city   dist  整租房源数量
0    上海     浦东     791
1    上海     闵行     286
2    上海     松江     261
3    上海     徐汇     214
4    上海     普陀     191
5    上海     嘉定     189
6    上海     长宁     180
7    上海     青浦     173
8    上海     宝山     167
9    上海     黄浦     111
10   上海     杨浦     108
11   上海     静安      91
12   上海     闸北      90
13   上海     虹口      78
14   上海     奉贤      57
15   北京     朝阳    1047
16   北京     海淀     328
17   北京     丰台     319
18   北京     大兴     221
19   北京     通州     219
20   北京     西城     198
21   北京     昌平     170
22   北京     房山     111
23   北京     顺义     107
24   北京    门头沟      91
25   北京     东城      64
26   北京    石景山      61
27   北京  亦庄开发区      56
28   广州     白云     662
29   广州     番禺     552
30   广州     天河     506
31   广州     增城     369
32   广州     海珠     263
33   广州     越秀     254
34   广州     荔湾     220
35   广州     南沙      51
36   深圳    宝安区     575
37   深圳    龙岗区     557
38   深圳    南山区     530
39   深圳    福田区     370
40   深圳    龙华区     317
41   深圳    罗湖区     228
42   深圳    光明区      68

## 三、行政区整租月租金比较

In [14]:
# 计算各行政区的整租房源数量
district_rent_count = entire_df.groupby(
    ["city", "dist"]
)["rent_price_num"].count()

In [15]:
# 计算各行政区的整租平均月租金
district_rent_mean = entire_df.groupby(
    ["city", "dist"]
)["rent_price_num"].mean().round(2)

In [16]:
# 计算各行政区的整租月租金中位数
district_rent_median = entire_df.groupby(
    ["city", "dist"]
)["rent_price_num"].median()

In [17]:
# 把三项结果组合成一张表
district_rent = pd.DataFrame({
    "整租房源数量": district_rent_count,
    "整租平均月租金": district_rent_mean,
    "整租月租金中位数": district_rent_median
})

district_rent = district_rent.reset_index()

district_rent = district_rent.sort_values(  # 排序优先级是：先按照city排序，让同一城市的行政区集中在一起；如果城市相同，再按照“整租月租金中位数”排序。
    by=["city", "整租月租金中位数"],
    ascending=[True, False]
)

district_rent = district_rent.reset_index(
    drop=True
)

district_rent

   city   dist  整租房源数量   整租平均月租金  整租月租金中位数
0    上海     静安      91  14999.45   13000.0
1    上海     黄浦     111  17476.05   12500.0
2    上海     长宁     180  13827.78   12000.0
3    上海     徐汇     214  10338.60    7000.0
4    上海     虹口      78   9169.08    6900.0
5    上海     普陀     191   8175.55    6500.0
6    上海     闸北      90  11217.78    6400.0
7    上海     闵行     286   9362.59    6250.0
8    上海     浦东     791  10122.47    6200.0
9    上海     杨浦     108   7263.89    5550.0
10   上海     青浦     173  10033.82    5300.0
11   上海     宝山     167   5410.18    4600.0
12   上海     松江     261   5844.18    4500.0
13   上海     嘉定     189   4973.26    4200.0
14   上海     崇明       1   4000.00    4000.0
15   上海     奉贤      57   2473.68    2300.0
16   上海     金山       4   1637.50    1500.0
17   北京     海淀     328  11191.13    8200.0
18   北京     朝阳    1047  11845.77    8000.0
19   北京     东城      64   8948.44    7800.0
20   北京     西城     198  10447.45    7500.0
21   北京  亦庄开发区      56   7243.75    6300.0
22   北京     丰台     319   7208.91    6000.0
23   北京     昌平     170   6836.47    5500.0
24   北京    石景山      61   6478.69    5300.0
25   北京     大兴     221   5888.24    4600.0
26   北京     通州     219   5453.88    4500.0
27   北京     顺义     107   6122.90    4500.0
28   北京     房山     111   3569.82    3200.0
29   北京    门头沟      91   3419.78    3000.0
30   广州     越秀     254   5859.53    4500.0
31   广州     天河     506   5321.14    4300.0
32   广州     海珠     263   4571.92    3800.0
33   广州     番禺     552   3560.79    3000.0
34   广州     白云     662   3344.60    3000.0
35   广州     增城     369   3047.50    2500.0
36   广州     荔湾     220   2640.42    2399.0
37   广州     南沙      51   2330.00    2300.0
38   广州     从化      21   1895.24    1800.0
39   深圳    南山区     530  12940.88    8500.0
40   深圳    福田区     370   9487.91    7400.0
41   深圳    罗湖区     228   6432.19    5750.0
42   深圳    盐田区      26   5092.69    4950.0
43   深圳    龙华区     317   5080.68    4000.0
44   深圳    龙岗区     557   3719.03    3150.0
45   深圳   大鹏新区       2   2800.00    2800.0
46   深圳    宝安区     575   3490.88    2130.0
47   深圳    坪山区       9   2186.67    1900.0
48   深圳    光明区      68   2680.78    1765.0

In [18]:
# 筛选可以参与月租金排名的行政区
district_rent_eligible = district_rent[
    district_rent["整租房源数量"] >= 30
].copy()

# 重新生成连续行号
district_rent_eligible = district_rent_eligible.reset_index(
    drop=True
)

print(
    "参与月租金排名的行政区数量：",
    len(district_rent_eligible)
)

district_rent_eligible

参与月租金排名的行政区数量： 43

   city   dist  整租房源数量   整租平均月租金  整租月租金中位数
0    上海     静安      91  14999.45   13000.0
1    上海     黄浦     111  17476.05   12500.0
2    上海     长宁     180  13827.78   12000.0
3    上海     徐汇     214  10338.60    7000.0
4    上海     虹口      78   9169.08    6900.0
5    上海     普陀     191   8175.55    6500.0
6    上海     闸北      90  11217.78    6400.0
7    上海     闵行     286   9362.59    6250.0
8    上海     浦东     791  10122.47    6200.0
9    上海     杨浦     108   7263.89    5550.0
10   上海     青浦     173  10033.82    5300.0
11   上海     宝山     167   5410.18    4600.0
12   上海     松江     261   5844.18    4500.0
13   上海     嘉定     189   4973.26    4200.0
14   上海     奉贤      57   2473.68    2300.0
15   北京     海淀     328  11191.13    8200.0
16   北京     朝阳    1047  11845.77    8000.0
17   北京     东城      64   8948.44    7800.0
18   北京     西城     198  10447.45    7500.0
19   北京  亦庄开发区      56   7243.75    6300.0
20   北京     丰台     319   7208.91    6000.0
21   北京     昌平     170   6836.47    5500.0
22   北京    石景山      61   6478.69    5300.0
23   北京     大兴     221   5888.24    4600.0
24   北京     通州     219   5453.88    4500.0
25   北京     顺义     107   6122.90    4500.0
26   北京     房山     111   3569.82    3200.0
27   北京    门头沟      91   3419.78    3000.0
28   广州     越秀     254   5859.53    4500.0
29   广州     天河     506   5321.14    4300.0
30   广州     海珠     263   4571.92    3800.0
31   广州     番禺     552   3560.79    3000.0
32   广州     白云     662   3344.60    3000.0
33   广州     增城     369   3047.50    2500.0
34   广州     荔湾     220   2640.42    2399.0
35   广州     南沙      51   2330.00    2300.0
36   深圳    南山区     530  12940.88    8500.0
37   深圳    福田区     370   9487.91    7400.0
38   深圳    罗湖区     228   6432.19    5750.0
39   深圳    龙华区     317   5080.68    4000.0
40   深圳    龙岗区     557   3719.03    3150.0
41   深圳    宝安区     575   3490.88    2130.0
42   深圳    光明区      68   2680.78    1765.0

In [19]:
# 找出每个城市月租金中位数最高的3个行政区
top_district_rent = district_rent_eligible.groupby(
    "city"
).head(3).copy()

top_district_rent = top_district_rent.reset_index(
    drop=True
)

print("结果行数：", len(top_district_rent))

top_district_rent

结果行数： 12

   city dist  整租房源数量   整租平均月租金  整租月租金中位数
0    上海   静安      91  14999.45   13000.0
1    上海   黄浦     111  17476.05   12500.0
2    上海   长宁     180  13827.78   12000.0
3    北京   海淀     328  11191.13    8200.0
4    北京   朝阳    1047  11845.77    8000.0
5    北京   东城      64   8948.44    7800.0
6    广州   越秀     254   5859.53    4500.0
7    广州   天河     506   5321.14    4300.0
8    广州   海珠     263   4571.92    3800.0
9    深圳  南山区     530  12940.88    8500.0
10   深圳  福田区     370   9487.91    7400.0
11   深圳  罗湖区     228   6432.19    5750.0

## 四、行政区整租每平方米租金比较

In [20]:
# 计算各行政区的整租房源数量
district_per_sqm_count = entire_df.groupby(
    ["city", "dist"]
)["rent_price_per_sqm"].count()

In [21]:
# 计算各行政区的整租平均每平方米租金
district_per_sqm_mean = entire_df.groupby(
    ["city", "dist"]
)["rent_price_per_sqm"].mean().round(2)

In [22]:
# 计算各行政区的整租每平方米租金中位数
district_per_sqm_median = entire_df.groupby(
    ["city", "dist"]
)["rent_price_per_sqm"].median().round(2)

In [23]:
# 把三项结果组合成一张表
district_per_sqm = pd.DataFrame({
    "整租房源数量": district_per_sqm_count,
    "整租平均每平方米租金": district_per_sqm_mean,
    "整租每平方米租金中位数": district_per_sqm_median
})

district_per_sqm = district_per_sqm.reset_index()  # 第一次不写drop=True：把city、dist从分组索引变成普通字段并保留。

district_per_sqm = district_per_sqm.sort_values(
    by=["city", "整租每平方米租金中位数"],
    ascending=[True, False]
)

district_per_sqm = district_per_sqm.reset_index(
    drop=True  # 第二次写drop=True：丢掉排序后的旧行号。
)

district_per_sqm

   city   dist  整租房源数量  整租平均每平方米租金  整租每平方米租金中位数
0    上海     静安      91      155.63       153.06
1    上海     黄浦     111      145.40       133.33
2    上海     长宁     180      133.87       128.80
3    上海     徐汇     214      125.90       115.58
4    上海     闸北      90      117.01       102.19
5    上海     虹口      78      106.47       100.00
6    上海     普陀     191       97.02        96.43
7    上海     杨浦     108       98.63        94.36
8    上海     浦东     791       85.96        81.36
9    上海     闵行     286       75.14        69.36
10   上海     宝山     167       59.05        57.14
11   上海     嘉定     189       55.32        52.77
12   上海     青浦     173       58.04        52.33
13   上海     松江     261       48.87        46.60
14   上海     崇明       1       36.70        36.70
15   上海     奉贤      57       29.82        27.83
16   上海     金山       4       23.50        25.26
17   北京     东城      64      138.79       129.17
18   北京     西城     198      134.23       125.40
19   北京     海淀     328      121.23       116.22
20   北京     朝阳    1047      120.39       113.40
21   北京     丰台     319       90.07        85.71
22   北京    石景山      61       89.44        85.57
23   北京  亦庄开发区      56       84.20        81.94
24   北京     通州     219       62.38        58.06
25   北京     昌平     170       63.21        57.66
26   北京     大兴     221       58.89        55.56
27   北京    门头沟      91       52.37        50.00
28   北京     顺义     107       57.95        50.00
29   北京     房山     111       49.29        44.44
30   广州     越秀     254       85.63        75.00
31   广州     天河     506       71.58        63.12
32   广州     海珠     263       63.83        60.00
33   广州     白云     662       48.87        44.16
34   广州     荔湾     220       45.54        41.32
35   广州     番禺     552       42.58        40.00
36   广州     南沙      51       32.87        27.69
37   广州     增城     369       32.94        27.40
38   广州     从化      21       19.44        17.78
39   深圳    南山区     530      132.63       121.67
40   深圳    福田区     370      125.41       116.76
41   深圳    罗湖区     228      102.19       100.00
42   深圳    龙华区     317       77.59        76.40
43   深圳    宝安区     575       72.91        70.00
44   深圳    龙岗区     557       60.18        56.82
45   深圳    盐田区      26       68.52        55.78
46   深圳   大鹏新区       2       47.88        47.88
47   深圳    光明区      68       52.11        46.62
48   深圳    坪山区       9       40.63        34.83

In [24]:
# 筛选可以参与单位面积租金排名的行政区
district_per_sqm_eligible = district_per_sqm[
    district_per_sqm["整租房源数量"] >= 30
].copy()

district_per_sqm_eligible = (
    district_per_sqm_eligible.reset_index(
        drop=True
    )
)

print(
    "参与单位面积租金排名的行政区数量：",
    len(district_per_sqm_eligible)
)

district_per_sqm_eligible

参与单位面积租金排名的行政区数量： 43

   city   dist  整租房源数量  整租平均每平方米租金  整租每平方米租金中位数
0    上海     静安      91      155.63       153.06
1    上海     黄浦     111      145.40       133.33
2    上海     长宁     180      133.87       128.80
3    上海     徐汇     214      125.90       115.58
4    上海     闸北      90      117.01       102.19
5    上海     虹口      78      106.47       100.00
6    上海     普陀     191       97.02        96.43
7    上海     杨浦     108       98.63        94.36
8    上海     浦东     791       85.96        81.36
9    上海     闵行     286       75.14        69.36
10   上海     宝山     167       59.05        57.14
11   上海     嘉定     189       55.32        52.77
12   上海     青浦     173       58.04        52.33
13   上海     松江     261       48.87        46.60
14   上海     奉贤      57       29.82        27.83
15   北京     东城      64      138.79       129.17
16   北京     西城     198      134.23       125.40
17   北京     海淀     328      121.23       116.22
18   北京     朝阳    1047      120.39       113.40
19   北京     丰台     319       90.07        85.71
20   北京    石景山      61       89.44        85.57
21   北京  亦庄开发区      56       84.20        81.94
22   北京     通州     219       62.38        58.06
23   北京     昌平     170       63.21        57.66
24   北京     大兴     221       58.89        55.56
25   北京    门头沟      91       52.37        50.00
26   北京     顺义     107       57.95        50.00
27   北京     房山     111       49.29        44.44
28   广州     越秀     254       85.63        75.00
29   广州     天河     506       71.58        63.12
30   广州     海珠     263       63.83        60.00
31   广州     白云     662       48.87        44.16
32   广州     荔湾     220       45.54        41.32
33   广州     番禺     552       42.58        40.00
34   广州     南沙      51       32.87        27.69
35   广州     增城     369       32.94        27.40
36   深圳    南山区     530      132.63       121.67
37   深圳    福田区     370      125.41       116.76
38   深圳    罗湖区     228      102.19       100.00
39   深圳    龙华区     317       77.59        76.40
40   深圳    宝安区     575       72.91        70.00
41   深圳    龙岗区     557       60.18        56.82
42   深圳    光明区      68       52.11        46.62

In [25]:
# 找出每个城市单位面积租金中位数最高的3个行政区
top_district_per_sqm = district_per_sqm_eligible.groupby(
    "city"
).head(3).copy()

top_district_per_sqm = top_district_per_sqm.reset_index(
    drop=True
)

print("结果行数：", len(top_district_per_sqm))

top_district_per_sqm

结果行数： 12

   city dist  整租房源数量  整租平均每平方米租金  整租每平方米租金中位数
0    上海   静安      91      155.63       153.06
1    上海   黄浦     111      145.40       133.33
2    上海   长宁     180      133.87       128.80
3    北京   东城      64      138.79       129.17
4    北京   西城     198      134.23       125.40
5    北京   海淀     328      121.23       116.22
6    广州   越秀     254       85.63        75.00
7    广州   天河     506       71.58        63.12
8    广州   海珠     263       63.83        60.00
9    深圳  南山区     530      132.63       121.67
10   深圳  福田区     370      125.41       116.76
11   深圳  罗湖区     228      102.19       100.00

## 五、统一检查行政区分析结果

In [26]:
# 统一检查第6天使用的数据和主要结果
print("清洗数据规模：", df.shape)
print("整租房源数量：", len(entire_df))
print("整租出租类型：", entire_df["type"].unique())

print("全部行政区数量：", len(district_counts))
print("参与排名的行政区数量：", len(district_per_sqm_eligible))
print("样本不足的行政区数量：", len(small_sample_districts))

print("月租金前3名结果行数：", len(top_district_rent))
print("单位面积租金前3名结果行数：", len(top_district_per_sqm))

print("\n各城市单位面积租金结果数量：")
print(
    top_district_per_sqm["city"].value_counts()
)

清洗数据规模： (11978, 26)
整租房源数量： 11564
整租出租类型： <StringArray>
['整租']
Length: 1, dtype: str
全部行政区数量： 49
参与排名的行政区数量： 43
样本不足的行政区数量： 6
月租金前3名结果行数： 12
单位面积租金前3名结果行数： 12

各城市单位面积租金结果数量：
city
上海    3
北京    3
广州    3
深圳    3
Name: count, dtype: int64

## 数据分析总结

### 数据基本情况

- 本次分析使用第3天生成的清洗数据，共11,978条住宅租房记录和26个字段。
- 行政区市场分析只使用11,564条整租房源，没有把整租和合租混合分析。
- 清洗数据共包含49个“城市＋行政区”组合。
- 为避免极少数房源代表整个行政区，正式排名只包括至少有30条整租样本的行政区。
- 共有43个行政区达到排名要求，6个行政区样本不足。
- 30条是本项目描述性排名使用的基础门槛，不是普遍适用的统计标准。
- 样本不足的行政区仍保留在完整统计结果中，没有删除房源或修改清洗数据。

### 主要分析结果

- 上海整租月租金中位数最高的3个合格行政区是静安、黄浦和长宁，分别为13,000元、12,500元和12,000元。
- 北京整租月租金中位数最高的3个合格行政区是海淀、朝阳和东城，分别为8,200元、8,000元和7,800元。
- 广州整租月租金中位数最高的3个合格行政区是越秀、天河和海珠，分别为4,500元、4,300元和3,800元。
- 深圳整租月租金中位数最高的3个合格行政区是南山区、福田区和罗湖区，分别为8,500元、7,400元和5,750元。
- 上海整租每平方米租金中位数最高的3个合格行政区是静安、黄浦和长宁，分别为153.06元、133.33元和128.80元。
- 北京整租每平方米租金中位数最高的3个合格行政区是东城、西城和海淀，分别为129.17元、125.40元和116.22元。
- 广州整租每平方米租金中位数最高的3个合格行政区是越秀、天河和海珠，分别为75.00元、63.12元和60.00元。
- 深圳整租每平方米租金中位数最高的3个合格行政区是南山区、福田区和罗湖区，分别为121.67元、116.76元和100.00元。
- 上海、广州和深圳的月租金前3名与每平方米租金前3名行政区相同。
- 北京的两项排名存在差异：朝阳进入月租金前3名，西城进入每平方米租金前3名，说明总租金排名会受到房屋面积影响。
- 以上结果描述当前清洗样本中的整租房源，不代表行政区全部租赁市场。